add_newline = true
follow_symlinks = false
continuation_prompt = '[▶▶ ](#51576d)'

format = """
[ ](bg:#e78284)\
$c\
$cmake\
$cobol\
$daml\
$dart\
$dotnet\
$elixir\
$elm\
$erlang\
$fennel\
$gleam\
$golang\
$guix_shell\
$haskell\
$haxe\
$helm\
$java\
$julia\
$kotlin\
$gradle\
$lua\
$nim\
$nodejs\
$ocaml\
$opa\
$perl\
$php\
$pulumi\
$purescript\
$python\
$quarto\
$raku\
$rlang\
$red\
$ruby\
$rust\
$scala\
$solidity\
$swift\
$terraform\
$typst\
$vlang\
$vagrant\
$zig\
$buf\
$conda\
$meson\
$spack\
$directory[ ](#e78284)\
( $git_branch )[](#414559)\
($git_status)$nix_shell
"""

right_format = "$character( $cmd_duration)"

[cmd_duration]
format = '[$duration](#e78284)'

# ~/.config/starship.toml

[nix_shell]
impure_msg = '[ ](#414559)'
pure_msg = '[󰂔]($style)[ ](#414559)'
unknown_msg = '[]($style)[ ](#414559)'
style = "bg:#414559 fg:#e78284"
format = '$state'

[character]
success_symbol = ''
error_symbol = '[](bold #e78284)'
vimcmd_symbol = '[](bold #ef9f76)'

[git_branch]
symbol = ""
format = "[$symbol $branch]($style)"
style = "#e78284"
[git_status]
format = "[$all_status]($style)"
style = "bg:#414559 fg:#e78284"

[directory]
style = "bg:#e78284 fg:#232634"
format = "[$path]($style)"
truncation_length = 1

[directory.substitutions]
"0" = " external"
"andriod" = " andriod"
"downloads" = " downloads"
".config" = " config"
"~" = " home"

[bun]
style = "bg:#e78284 fg:#232634"
format = "[$symbol]($style)"

[buf]
symbol = " "
style = "bg:#e78284 fg:#232634"
format = "[$symbol]($style)"

[cmake]
style = "bg:#e78284 fg:#232634"
format = "[$symbol]($style)"

[cobol]
style = "bg:#e78284 fg:#232634"
format = "[$symbol]($style)"

[crystal]
symbol = " "
style = "bg:#e78284 fg:#232634"
format = "[$symbol]($style)"

[daml]
style = "bg:#e78284 fg:#232634"
format = "[$symbol]($style)"

[dart]
symbol = " "
style = "bg:#e78284 fg:#232634"
format = "[$symbol]($style)"

[deno]
style = "bg:#e78284 fg:#232634"
format = "[$symbol]($style)"

[dotnet]
style = "bg:#e78284 fg:#232634"
format = "[$symbol]($style)"

[elixir]
symbol = " "
style = "bg:#e78284 fg:#232634"
format = '[$symbol]($style)'

[elm]
symbol = " "
style = "bg:#e78284 fg:#232634"
format = '[$symbol]($style)'

[erlang]
style = "bg:#e78284 fg:#232634"
format = '[$symbol]($style)'

[fennel]
symbol = " "
style = "bg:#e78284 fg:#232634"
format = '[$symbol]($style)'

[gleam]
style = "bg:#e78284 fg:#232634"
format = '[$symbol]($style)'

[golang]
symbol = " "
style = "bg:#e78284 fg:#232634"
format = '[$symbol]($style)'

[gradle]
symbol = " "
style = "bg:#e78284 fg:#232634"
format = '[$symbol]($style)'

[haxe]
symbol = " "
style = "bg:#e78284 fg:#232634"
format = '[$symbol]($style)'

[helm]
style = "bg:#e78284 fg:#232634"
format = '[$symbol]($style)'

[java]
symbol = " "
style = "bg:#e78284 fg:#232634"
format = '[$symbol]($style)'

[julia]
symbol = " "
style = "bg:#e78284 fg:#232634"
format = '[$symbol]($style)'

[kotlin]
symbol = " "
style = "bg:#e78284 fg:#232634"
format = '[$symbol]($style)'

[lua]
symbol = " "
style = "bg:#e78284 fg:#232634"
format = '[$symbol]($style)'

[meson]
symbol = "󰔷 "
style = "bg:#e78284 fg:#232634"
format = '[$symbol]($style)'

[nim]
symbol = "󰆥 "
style = "bg:#e78284 fg:#232634"
format = '[$symbol]($style)'

[nodejs]
symbol = " "
style = "bg:#e78284 fg:#232634"
format = '[$symbol]($style)'

[ocaml]
symbol = " "
style = "bg:#e78284 fg:#232634"
format = '[$symbol(\($switch_indicator$switch_name\) )]($style)'

[opa]
style = "bg:#e78284 fg:#232634"
format = '[$symbol]($style)'

[perl]
symbol = " "
style = "bg:#e78284 fg:#232634"
format = '[$symbol]($style)'

[php]
symbol = " "
style = "bg:#e78284 fg:#232634"
format = '[$symbol]($style)'

[pulumi]
style = "bg:#e78284 fg:#232634"
format = '[$symbol$stack]($style)'

[purescript]
style = "bg:#e78284 fg:#232634"
format = '[$symbol]($style)'

[python]
symbol = " "
style = "bg:#e78284 fg:#232634"
format = '[$symbol]($style)'

[quarto]
style = "bg:#e78284 fg:#232634"
format = '[$symbol]($style)'

[raku]
style = "bg:#e78284 fg:#232634"
format = '[$symbol]($style)'

[red]
style = "bg:#e78284 fg:#232634"
format = '[$symbol]($style)'

[rlang]
symbol = "󰟔 "
style = "bg:#e78284 fg:#232634"
format = '[$symbol]($style)'

[ruby]
symbol = " "
style = "bg:#e78284 fg:#232634"
format = '[$symbol]($style)'

[rust]
symbol = "󱘗 "
style = "bg:#e78284 fg:#232634"
format = '[$symbol]($style)'

[solidity]
style = "bg:#e78284 fg:#232634"
format = '[$symbol]($style)'

[typst]
style = "bg:#e78284 fg:#232634"
format = '[$symbol]($style)'

[swift]
symbol = " "
style = "bg:#e78284 fg:#232634"
format = '[$symbol]($style)'

[vagrant]
style = "bg:#e78284 fg:#232634"
format = '[$symbol]($style)'

[vlang]
style = "bg:#e78284 fg:#232634"
format = '[$symbol]($style)'

[zig]
symbol = " "
style = "bg:#e78284 fg:#232634"
format = '[$symbol]($style)'

[aws]
symbol = "  "
style = "bg:#e78284 fg:#232634"

[c]
symbol = ""
format = '[$symbol]($style)'
style = "bg:#e78284 fg:#232634"

[conda]
symbol = " "
style = "bg:#e78284 fg:#232634"

[docker_context]
style = "bg:#e78284 fg:#232634"
symbol = " "

[fossil_branch]
symbol = " "
style = "bg:#e78284 fg:#232634"

[git_commit]
tag_symbol = '  '
style = "bg:#e78284 fg:#232634"

[guix_shell]
symbol = " "
style = "bg:#e78284 fg:#232634"

[haskell]
symbol = " "
style = "bg:#e78284 fg:#232634"

[hg_branch]
symbol = " "
style = "bg:#e78284 fg:#232634"

[hostname]
ssh_symbol = " "
style = "bg:#e78284 fg:#232634"

[memory_usage]
symbol = "󰍛 "
style = "bg:#e78284 fg:#232634"

[os.symbols]
alpaquita = " "
alpine = " "
almalinux = " "
amazon = " "
android = " "
arch = " "
artix = " "
centos = " "
debian = " "
dragonfly = " "
emscripten = " "
endeavouros = " "
fedora = " "
freebsd = " "
garuda = "󰛓 "
gentoo = " "
hardenedbsd = "󰞌 "
illumos = "󰈸 "
kali = " "
linux = " "
mabox = " "
macos = " "
manjaro = " "
mariner = " "
midnightbsd = " "
mint = " "
netbsd = " "
nixos = " "
openbsd = "󰈺 "
opensuse = " "
oraclelinux = "󰌷 "
pop = " "
raspbian = " "
redhat = " "
redhatenterprise = " "
rockylinux = " "
redox = "󰀘 "
solus = "󰠳 "
suse = " "
ubuntu = " "
unknown = " "
void = " "
windows = "󰍲 "

[package]
symbol = "󰏗 "

[pijul_channel]
symbol = " "

[scala]
symbol = " "



